---
- hosts: localhost
  become: yes
  tasks:
  - name : Provide sudo access
    blockinfile:
      path: /etc/sudoers
      insertafter: 'root  ALL=(ALL)    ALL'
      block: |
          ansible ALL=(ALL) NOPASSWD: ALL
