---
- name: Transfer and execute a script.
  hosts: all
  remote_user: root
  tasks:
     - name: Transfer the script
       copy: src=/tmp/avinesh/s_status.sh dest=/test/avinesh mode=0755

     - name: Execute the script
       command: sh /tmp/avinesh/s_status.sh
